fix: android cancel
combateafraude/caf-identity-rn pull request #2
Opened 2023-11-27 14:53 UTC by guiialmeiida

2023-11-27 17:49 UTC, guiialmeiida commented on android/app/src/main/java/com/cafbridge_identity/CafIdentityActivity.java
> +                        message = "Cancelado pelo usuário";
Pode colocar a mesma mensagem só que em inglês

2023-11-27 18:00 UTC, murilofank commented on android/app/src/main/java/com/cafbridge_identity/CafIdentityActivity.java
> +                        message = "Cancelado pelo usuário";
Tem que alterar na bridge do iOS tbm a mesma mensagem!

2023-11-27 18:02 UTC, murilofank commented on ios/cafbridge_identity.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = D5N35VF3JG;
é um arquivo de configuração que o Xcode gera

2023-11-27 20:31 UTC, murilofank requested changes
Ajustar a mensagem de retorno do evento Canceled nas bridges Android e iOS. Retornar a mensagem em inglês "User canceled the action".

2023-11-27 21:01 UTC, murilofank requested changes

2023-11-27 21:17 UTC, murilofank submitted a review, later dismissed

2023-11-28 12:42 UTC, glaucocaf submitted a review, later dismissed
👍

2023-11-28 12:49 UTC, glaucocaf approved these changes
👍

2023-11-28 12:50 UTC, merged